### ISSUE TITLE
Message bottleneck

### ISSUE THREAD

**Issue by jhw** [schlagert/syslog#3]
Hi,

I'm trying to use syslog to talk to Papertrail

https://papertrailapp.com/

Have managed to get the two to talk to one another except that when a large message / group of large messages are sent by my app, communication with Papertrail appears to stop, possibly mid- message; and no further messages are received by Papertrail until the app has been restarted

Setting {no_progress, true} helps somewhat but communication still seems to cease if a large error message / stack trace is sent

It's as if some kind of bottleneck is being reached on the client side; do you have any tips for either increasing the throughput of messages or logging messages to check they are being sent ? I am reasonably sure the issue is on the client side rather than the Papertrail side

Thx,

Justin

**Comment by jhw** [comment]
I think I may be falling foul of this

https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=syslog%20max%20message%20size

:-(

**Comment by schlagert** [comment]
Hi Justin,

that might be your problem, the syslog application does not truncate
messages (yet). However, there are other possible pitfalls. Syslog uses UDP
as transport protocol and it does everything to protect the logger's
message queue. Did you already experiment with the msg_queue_limit? Did you
check the kernel stats for packet drops?

Sorry for this short answer, I'm writing this from a tablet which is just a
pain. If desired, I'll answer your questions in-depth on monday from my
desk.

Regards
Tobias
Am 01.01.2016 18:50 schrieb "jhw" <notifications@github.com>:

**Comment by jhw** [comment]
Hi Tobias,

Thank you so much for the quick response.

Weirdly the problem seems to be related to the configuration of dest_host; if I use the following -

{dest_host, "logs3.papertrailapp.com"}

then everything is fine; but if I use the following (was messing around with different options earlier, trying to get it to work) - 

{dest_host, {173,247,107,218}}

then I run into the problems mentioned.

Certainly it doesn't seem to be a size issue as I can do (eg)

syslog:info_msg([65 || _ <- lists:seq(1, 2000)]).

and the message appears fine in Papertrail.

As it happens I will probably run with {no_progress, true} as otherwise the volume of progress messages slows down Papertrail live logging quite a bit.

So I am hoping this may be the answer.

Just one final question - do I need to do anything special to capture crash reports ? Or are these passed to syslog by default ? Want to make sure that if the app goes down unexpectedly that crash messages are logged.

Many thanks,

Justin

**Comment by schlagert** [comment]
Glad you could solve your issue!

Crash reports are always captured and sent to/with the standard facility
unless specified otherwise (see `crash_facility`). The `no_progress` flag
disables only the supervisor reports generated when a new child gets
started. In production we also disable progress reports.

Regards
Tobias

**Comment by jhw** [comment]
That's great, thanks. Are crash reports sent as error (log- level) messages ? Or critical ?

**Comment by schlagert** [comment]
If I remember correctly, they get sent with severity `error` (3).

**Comment by jhw** [comment]
Many thanks.

**Comment by schlagert** [comment]
Hi Justin,

do you need further advice or may I close the issue?

**Comment by jhw** [comment]
I'm all sorted now. Thank you very much for your help.

**Comment by jhw** [comment]
Hi Tobias,

I am loving your syslog library but have one small issue and wondered if
you might have a second at some point

https://github.com/schlagert/syslog/issues/5

Best wishes and thanks,

Justin
