### ISSUE TITLE
IP address forwarded to Papertrail

### ISSUE THREAD

**Issue by jhw** [schlagert/syslog#5]
Hi Tobias,

Your syslog library is working fantastically for me, so many thanks.

However I have one question.

My current config is as follows (obfuscated):

[{syslog, [{dest_host, "logsXXX.papertrailapp.com"},
	   {dest_port, 12345},
	   {verbose, false},
	   {no_progress, true}]}].

Each message received by Papertrail is logged under an 'event', which loosely translates into the hostname / IP address from which the message was received. To quote Papertrail support -

"Papertrail does use the IP when a syslog packet is malformed and we need something to identify it, but otherwise we either use a hardcoded value that's set by the user, or what the sender provides" (for the 'event' name)

Now the weird thing is that it doesn't seem to matter where my app is hosted - whether localhost, EC2 or Linode; Papertrail always logs the event under '127'

Obviously '127' is short for '127.0.0.1'. Now it's possible that there is a problem on the Papertrail side, but the Papertrail guys are saying that I must be sending the messages with 127/127.0.0.1

Is this possible / likely given my config / your understanding of the library ? I have looked through the list of additional config options to see if there's something else I should add, but it's not clear to me what I might change.

Many thanks,

Justin

PS the issue for me is that if everything is logged to '127' by Papertrail, it's difficult/impossible to distinguish between development and production log messages

TIA

**Comment by schlagert** [comment]
Hi Justin,

I already habe some ideas regarding your issue. I'll comment tomorrow morning (CET) from the office.

Regards
Tobias

**Comment by jhw** [comment]
Thank you very much; sorry for the trouble.

**Comment by schlagert** [comment]
Hi Justin,

first of all you should verify were exactly the `127` gets originated. `syslog` uses `inet:gethostname/0` to get the hostname of the machine (this is what gets included in the messages). This should not return an IP address (at least not if your node is *alive*). You could check what that returns on your machine(s) when calling it from the Erlang shell of your node(s).

Next step could be to observe the outgoing `syslog` messages using `tcpdump`. A simple command that will print all traffic on port 514 (ASCII-interpreted) to the console is `tcpdump -A 'port 514'`. It could be useful to paste an example message as a comment.

Finally, if there's a problem with the RFC 5424 protocol format generated by `syslog` you cloud try to include the *UTF-8 BOM*. The *BOM* should be part of RFC compliant messages but is omitted by default because older versions of `rsyslog` and `syslog-ng` don't handle it well. Set the configuration `{use_rfc5424_bom, true}` to include the *UTF-8 BOM* in your messages.

Please let me know how this is working out, I'll try to help where I can.

**Comment by jhw** [comment]
Thank you very much. Will be a few days before I can take a look at this
but I will let you know.

Rgds -

Justin

**Comment by jhw** [comment]
Hi Tobias

>>> first of all you should verify were exactly the 127 gets originated.
syslog usesinet:gethostname/0 to get the hostname of the machine (this is
what gets included in the messages). This should not return an IP address
(at least not if your node is*alive*). You could check what that returns on
your machine(s) when calling it from the Erlang shell of your node(s).

My EC2 prod machine returns 'ip-172-31-0-229' for inet:gethostname/0; could
this be being mapped/converted to '127' somehow ? (I don't think so)

>>> Next step could be to observe the outgoing syslog messages using tcpdump.
A simple command that will print all traffic on port 514
(ASCII-interpreted) to the console istcpdump -A 'port 514'. It could be
useful to paste an example message as a comment.

I wasn't able to capture any traffic using 'sudo tcpdump  -A 'port 514';
I'm not a tcp expert at all, would 'eth0' be the right device to listen on ?

>>> Finally, if there's a problem with the RFC 5424 protocol format
generated by syslogyou cloud try to include the *UTF-8 BOM*. The *BOM* should
be part of RFC compliant messages but is omitted by default because older
versions of rsyslog and syslog-ngdon't handle it well. Set the
configuration {use_rfc5424_bom, true} to include the*UTF-8 BOM* in your
messages.

{use_rfc5424_bom, true} didn't seem to make any difference; messages still
logged until '127' by Papertrail

I will keep digging -

Thanks,

Justin

**Comment by schlagert** [comment]
Hi Justin,

sorry for the `tcpdump` command. You'll have to replace the port number with the port configured as `dest_port`. The `-A` Option will automatically capture the traffic of all interfaces except loopback.

I see that `inet:gethostname/0` returns a short hostname, no FQDN. Does your node name include the domain? I had a look at the code and found that the hostname used is the host part of the node name. Maybe papertrail doesn't like short hostnames when RFC 5424 is used (which normally requires the fully qualified hostname).

Regards
Tobias

**Comment by jhw** [comment]
>>> Does your node name include the domain? I had a look at the code and
found that the hostname used is the host part of the node name.

Aaaaah I think you make have it there. I use an Erlang,mk default setup
which sets node name as 'app_name@127.0.0.1'. You say your library uses the
hostname part of the node name .. if it's in the form above, what would it
send to Papertrail ?

Thank you

**Comment by schlagert** [comment]
There we have the problem! In this case it would send `127.0.0.1` as hostname.  It would be best to set the node name to meaningful value.

Nevertheless, thanks for pointing that out! The hostname handling is definitly a weakness I will work on.

Regards
Tobias

**Comment by jhw** [comment]
That's great, thank you very much.

**Comment by jhw** [comment]
Hi Tobias,

Thinking some more about this.

I would really like to be able to have your library report
inet:gethostname() as the host name.

Looking at you code in syslog_lib.erl

get_hostname()                -> get_hostname(atom_to_list(node())).
get_hostname("nonode@nohost") -> {ok, Hostname} = inet:gethostname(),
Hostname;
get_hostname(Node)            -> hd(lists:reverse(string:tokens(Node,
"@"))).

It seems the only way to do this is to specify "nonode@nohost" as the node
name.

However if I do this, I run into this error

http://stackoverflow.com/questions/28515679/erlang-release-set-node-name-for-bin-xxxxx-start-name-nonodenohost

ie error_logger crashes

So I don't think there's a way to do this right now.

Should I / could I submit a patch for what I think might be the right
behaviour ?

Rgds,

Justin

**Comment by schlagert** [comment]
Hi Justin,

the first thing I would do is to fix the hostname of the release, e.g. set it to `app_name` without the hostname part. Erlang will then do the correct thing for you.

Regards
Tobias

**Comment by schlagert** [comment]
Sorry, I meant fix the node name not the hostname ;-)

**Comment by jhw** [comment]
I can do that but it won't fix my main problem which is that I want my
syslog messages to differentiate between dev ip address (127.0.0.1) and
prod ip addresses (ec2, Linode). Just setting the node name to "app_name"
will mean both dev and prod ips will log as "app_name" (if i interpret code
correctly)

**Comment by schlagert** [comment]
No, if you do not specify a host part, the erlang runtime will resolve the
correct host part for you. The only time you need to specify the host part
is when name resolution is not working in your environment.
Am 31.01.2016 3:03 nachm. schrieb "jhw" <notifications@github.com>:
>
> I can do that but it won't fix my main problem which is that I want my
> syslog messages to differentiate between dev ip address (127.0.0.1) and
> prod ip addresses (ec2, Linode). Just setting the node name to "app_name"
> will mean both dev and prod ips will log as "app_name" (if i interpret
code
> correctly)

**Comment by jhw** [comment]
So assuming I just use "app_name" for the node name, syslog will resolve
the host name for me *and* include that host name as part of the syslog
message ?

**Comment by schlagert** [comment]
Sorry, for my short answer, the phone keypad is just horrible. 

This has nothing to do with syslog. Just try `erl -name app_name` in the shell and look at the node name Erlang will come up with. I'm pretty shure that the host part of this node name will be what you want.

Regards
Tobias

**Comment by jhw** [comment]
I will try. Thank you. Please excuse me if these are basic Erlang questions
:-)

**Comment by schlagert** [comment]
No problem, I'm glad I could help.

By the way, the template is really not providing the best and intuitive value here :-/

**Comment by jhw** [comment]
>>> Just try erl -name app_name in the shell and look at the node name
Erlang will come up with

Did you mean 'erl -sname app_name'  ?

'erl -name app_name' crashes the VM as I don't think app_name is a valid
long name

However  'erl -sname app_name'  returns a node name of

'app_name@justin-ThinkPad-X240'

So I think this might be what I'm looking for

??

**Comment by jhw** [comment]
Works!

OK the solution is to use a short node name ('sname') (eg 'app_name')
rather than a long node name (eg 'app_name@127.0.0.01'); then everything
works just fine.

Thank you for your patience :-)

Justin

**Comment by schlagert** [comment]
> 'erl -name app_name' crashes the VM as I don't think app_name is a valid long name

Using the above command will work, if name resolution works in your network domain, e.g. at work this works perfectly on my machine (as it most probably will in an EC2 environment). At home I also can't use the command because I don't have a DNS server running and my machine only has a short hostname. The `-name` and `-sname` arguments correspond to the host part of the node name only.

I just pushed a little update to `master` that handles cases with node names related to the `loopback` interface. Additionally, the domain name handling was a bit quirky when IP addresses have been used in node names.

Glad that everything worked out for you! May I close the issue?

**Comment by jhw** [comment]
>>> Glad that everything worked out for you! May I close the issue?

Yes, absolutely.

I will pull the new version.

Many thanks again.
