### ISSUE TITLE
STRUCTURED-DATA

### ISSUE THREAD

**Issue by adrianboston** [schlagert/syslog#9]
Is it possible to utilize structured data fields in this nice syslog

**Comment by schlagert** [comment]
Unfortunately this is still not possible. I always had plans to support it but never got the time to implement it.

**Comment by adrianboston** [comment]
where would i start ?
hehe

**Comment by schlagert** [comment]
The `syslog_rfc5424.erl` would be the correct file to place encoding logic into. The file `syslog_logger.erl` is where the encoding functions get called.

What kind of terms would you like to put into the structured data section?

**Comment by schlagert** [comment]
I would suggest something like `{SD-ID :: term(), SD-PARAMS :: proplists:proplists()}`.

**Comment by adrianboston** [comment]
im seeking to do some kibana and some of the logging (ELK) services dont have groking on the logstash side because they are not actually using logstash but proprietary loggers. the problem is kibana accepts unique fields only and cannot grok on its own. seperate fields would be accepted without a logstash equiv.

**Comment by adrianboston** [comment]
thanks for your comments.

**Comment by adrianboston** [comment]
on another note, it seems that some of the variables are not set..

    application:load(syslog),
    Host = "blah",
    ok = application:set_env(syslog, dest_host, Host),
    application:start(syslog),

    is there another way of setting the variables and starting without using a config file??

**Comment by schlagert** [comment]
Sorry if I misunderstood your last comment.

You should definitely use an Erlang release for your application. Application configuration will then be part of the release. However, the `syslog` application has default values for all configuration parameters. The default configuration is to send RFC 3164 formatted messages via UDP to `127.0.0.1:514`.

If you want to start the `syslog` application from your own application you can overwrite the values like you did using `application:set_env/2,3`. Make sure `syslog` is not running. Initially load the application (the Erlang runtime will then load the values from the `syslog.app` file into the application environment) as you did. Finally, overwrite the application environment values you want to modify and start the application.

If I remember correctly, `syslog`'s default environment should be empty. All default values are defined in the source files and get pulled in if a configuration parameter is not set in the environment, similar to using `application:get_env/3`.

**Comment by adrianboston** [comment]
i pull user defined parameters (from a friendlier .ini file format) and then use application:set_env/2,3 

its a release -- using rebar3.

application:get_all_env(syslog)  shows all the newly set env variables.  for sure they are not.

when those env variables are in config.sys then it is functioning as expected.

im guessing its started already?!

**Comment by adrianboston** [comment]
ok = application:set_env(syslog, log_level, "debug")
string opposed to an atom.

**Comment by schlagert** [comment]
Ok, now I get it.

The Erlang release will automatically start the contained applications. Thus trying to configure `syslog` afterwards does not have any effect, since `syslog` reads its configuration values only on application startup (for performance). If you want to reconfigure the application you will need to restart it.

You might have a look at `syslog_tests:setup_apps/3` in the `test` folder. It applies different configurations programmatically for the different test cases.

**Comment by schlagert** [comment]
I just had some free time and added support for STRUCTURED-DATA. I hope it's of use for you.

**Comment by adrianboston** [comment]
ill try out the STRUCTURED-DATA addition. thanks

**Comment by schlagert** [comment]
If more questions arise on this topic, just re-open this issue.
